import Discord from "@/components/discord";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>subscriptado</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="max-w-screen-lg p-5 w-full md:py-10 md:w-10/12 lg:py-20 lg:w-8/12 mx-auto transition-all duration-300">
        <div>
          <div className="container mx-auto pt-8">
            <section className="mt-20">
              <div className="flex items-center justify-center text-center w-full">
                <div className="flex flex-col">
                  <h1 className="text-transparent text-5xl text-center font-bold leading-[3.5rem] bg-clip-text bg-gradient-to-b from-zinc-400 to-white">
                    Hi there, I&apos;m <span className="text-transparent bg-clip-text bg-gradient-to-b from-amber-800 to-amber-500">subsc</span>
                  </h1>
                  <h3 className="text-zinc-400 transition-all duration-200 mt-3">
                    FrontEnd Developer. My name is subscrip, i live in Brazil
                  </h3>
                </div>
              </div>
            </section>
          </div>
        </div>
      </header>
      <section className="px-12 md:px-20 lg:px-32 pt-28 flex justify-center items-center flex-col md:flex-row relative z-[1]">
        <div className="hidden md:block w-1/2 flex justify-center items-center flex-col">
          <Discord />
        </div>
        <div className="md:hidden w-full flex justify-center items-center">
          <Discord />
        </div>
        <div className="w-full md:w-1/2 lg:pl-12 flex justify-center items-center md:items-start flex-col text-center md:text-left">
          <h1 className="text-primary-light font-bold m-0 my-6 md:mt-0 p-0 pb-1 shadow select-none text-3xl md:text-5xl" style={{ background: "linear-gradient(0deg, rgba(236,236,236,1) 0%, rgba(202,200,217,1) 100%)", backgroundSize: "100%", backgroundClip: "text", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent" }}>About me</h1>
          <h3 className="text-zinc-400 text-center shadow md:text-left md:text-xl m-0 md:mr-3 p-0">Hello everyone, my name is subscriptado. I&apos;ve been making bots for discord for over 2 years and I&apos;m starting my path on the front-end, using nextjs and tailwind css</h3>
        </div>
      </section>
      <section className="mt-10"></section>
    </>
  );
}
